### ISSUE TITLE
 node scripts/postinstall.js error during installation

### ISSUE THREAD

**Issue by paul-hammant** [cucumber/cucumber-expressions-javascript#2]
apt-get packages : up to date today
npm packages : up to date today

Other npm installables work fine.  It is 'cucumber' I'm trying to install via npm, and it has a transitive dep to -expressions of course.

Log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'cucumber-expressions' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData cucumber-expressions
8 silly fetchNamedPackageData cucumber-expressions
9 silly mapToRegistry name cucumber-expressions
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/cucumber-expressions
13 verbose request uri https://registry.npmjs.org/cucumber-expressions
14 verbose request no auth needed
15 info attempt registry request try #1 at 10:36:21 AM
16 verbose request id 8c30826b5441a56f
17 verbose etag W/"58c09bd9-326f"
18 verbose lastModified Thu, 09 Mar 2017 00:03:37 GMT
19 http request GET https://registry.npmjs.org/cucumber-expressions
20 http 304 https://registry.npmjs.org/cucumber-expressions
21 verbose headers { date: 'Thu, 13 Apr 2017 14:36:40 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   etag: 'W/"58c09bd9-326f"',
21 verbose headers   age: '125',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-jfk8150-JFK',
21 verbose headers   'x-cache': 'HIT',
21 verbose headers   'x-cache-hits': '18',
21 verbose headers   'x-timer': 'S1492094201.964142,VS0,VE0',
21 verbose headers   vary: 'Accept-Encoding' }
22 silly get cb [ 304,
22 silly get   { date: 'Thu, 13 Apr 2017 14:36:40 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     'cache-control': 'max-age=300',
22 silly get     etag: 'W/"58c09bd9-326f"',
22 silly get     age: '125',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-jfk8150-JFK',
22 silly get     'x-cache': 'HIT',
22 silly get     'x-cache-hits': '18',
22 silly get     'x-timer': 'S1492094201.964142,VS0,VE0',
22 silly get     vary: 'Accept-Encoding' } ]
23 verbose etag https://registry.npmjs.org/cucumber-expressions from cache
24 verbose get saving cucumber-expressions to /home/chrx/.npm/registry.npmjs.org/cucumber-expressions/.cache.json
25 silly install normalizeTree
26 silly loadCurrentTree Finishing
27 silly loadIdealTree Starting
28 silly install loadIdealTree
29 silly cloneCurrentTree Starting
30 silly install cloneCurrentTreeToIdealTree
31 silly cloneCurrentTree Finishing
32 silly loadShrinkwrap Starting
33 silly install loadShrinkwrap
34 silly loadShrinkwrap Finishing
35 silly loadAllDepsIntoIdealTree Starting
36 silly install loadAllDepsIntoIdealTree
37 silly resolveWithNewModule cucumber-expressions@3.0.0 checking installable status
38 silly cache add args [ 'cucumber-expressions', null ]
39 verbose cache add spec cucumber-expressions
40 silly cache add parsed spec Result {
40 silly cache add   raw: 'cucumber-expressions',
40 silly cache add   scope: null,
40 silly cache add   name: 'cucumber-expressions',
40 silly cache add   rawSpec: '',
40 silly cache add   spec: 'latest',
40 silly cache add   type: 'tag' }
41 silly addNamed cucumber-expressions@latest
42 verbose addNamed "latest" is being treated as a dist-tag for cucumber-expressions
43 info addNameTag [ 'cucumber-expressions', 'latest' ]
44 silly mapToRegistry name cucumber-expressions
45 silly mapToRegistry using default registry
46 silly mapToRegistry registry https://registry.npmjs.org/
47 silly mapToRegistry uri https://registry.npmjs.org/cucumber-expressions
48 verbose addNameTag registry:https://registry.npmjs.org/cucumber-expressions not in flight; fetching
49 verbose get https://registry.npmjs.org/cucumber-expressions not expired, no request
50 silly addNameTag next cb for cucumber-expressions with tag latest
51 silly addNamed cucumber-expressions@3.0.0
52 verbose addNamed "3.0.0" is a plain semver version for cucumber-expressions
53 silly cache afterAdd cucumber-expressions@3.0.0
54 verbose afterAdd /home/chrx/.npm/cucumber-expressions/3.0.0/package/package.json not in flight; writing
55 verbose afterAdd /home/chrx/.npm/cucumber-expressions/3.0.0/package/package.json written
56 silly loadAllDepsIntoIdealTree Finishing
57 silly idealTree:prePrune lib
57 silly idealTree:prePrune └── cucumber-expressions@3.0.0
58 silly loadIdealTree Finishing
59 silly currentTree lib
60 silly idealTree lib
60 silly idealTree └── cucumber-expressions@3.0.0
61 silly generateActionsToTake Starting
62 silly install generateActionsToTake
63 silly generateActionsToTake Finishing
64 silly diffTrees action count 1
65 silly diffTrees add cucumber-expressions@3.0.0
66 silly decomposeActions action count 8
67 silly decomposeActions fetch cucumber-expressions@3.0.0
68 silly decomposeActions extract cucumber-expressions@3.0.0
69 silly decomposeActions test cucumber-expressions@3.0.0
70 silly decomposeActions preinstall cucumber-expressions@3.0.0
71 silly decomposeActions build cucumber-expressions@3.0.0
72 silly decomposeActions install cucumber-expressions@3.0.0
73 silly decomposeActions postinstall cucumber-expressions@3.0.0
74 silly decomposeActions finalize cucumber-expressions@3.0.0
75 silly executeActions Starting
76 silly install executeActions
77 silly doSerial global-install 0
78 silly doParallel fetch 1
79 verbose lock using /home/chrx/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
80 silly doParallel extract 1
81 silly extract cucumber-expressions@3.0.0
82 verbose unbuild lib/node_modules/.staging/cucumber-expressions-343a18f0
83 silly gentlyRm /usr/local/lib/node_modules/.staging/cucumber-expressions-343a18f0 is being purged from base /usr/local
84 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/.staging/cucumber-expressions-343a18f0
85 verbose tar unpack /home/chrx/.npm/cucumber-expressions/3.0.0/package.tgz
86 verbose tar unpacking to /usr/local/lib/node_modules/.staging/cucumber-expressions-343a18f0
87 silly gentlyRm /usr/local/lib/node_modules/.staging/cucumber-expressions-343a18f0 is being purged
88 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/.staging/cucumber-expressions-343a18f0
89 silly gunzTarPerm modes [ '755', '644' ]
90 silly gunzTarPerm extractEntry package.json
91 silly gunzTarPerm extractEntry .npmignore
92 silly gunzTarPerm extractEntry README.md
93 silly gunzTarPerm extractEntry LICENSE
94 silly gunzTarPerm extractEntry dist/argument.js
95 silly gunzTarPerm extractEntry dist/build_arguments.js
96 silly gunzTarPerm extractEntry dist/cucumber_expression.js
97 silly gunzTarPerm extractEntry dist/cucumber_expression_generator.js
98 silly gunzTarPerm extractEntry dist/generated_expression.js
99 silly gunzTarPerm extractEntry dist/index.js
100 silly gunzTarPerm extractEntry dist/parameter_type.js
101 silly gunzTarPerm extractEntry dist/parameter_type_matcher.js
102 silly gunzTarPerm extractEntry dist/parameter_type_registry.js
103 silly gunzTarPerm extractEntry dist/regular_expression.js
104 silly gunzTarPerm extractEntry Makefile
105 silly gunzTarPerm extractEntry .babelrc
106 silly gunzTarPerm extractEntry .eslintrc.yml
107 silly gunzTarPerm extractEntry examples.txt
108 silly gunzTarPerm extractEntry mocha
109 silly gunzTarPerm extractEntry src/argument.js
110 silly gunzTarPerm extractEntry src/build_arguments.js
111 silly gunzTarPerm extractEntry src/cucumber_expression.js
112 silly gunzTarPerm extractEntry src/cucumber_expression_generator.js
113 silly gunzTarPerm extractEntry src/generated_expression.js
114 silly gunzTarPerm extractEntry src/index.js
115 silly gunzTarPerm extractEntry src/parameter_type.js
116 silly gunzTarPerm extractEntry src/parameter_type_matcher.js
117 silly gunzTarPerm extractEntry src/parameter_type_registry.js
118 silly gunzTarPerm extractEntry src/regular_expression.js
119 silly gunzTarPerm extractEntry .travis.yml
120 silly gunzTarPerm extractEntry scripts/postinstall.js
121 silly gunzTarPerm extractEntry test/assert_throws.js
122 silly gunzTarPerm extractEntry test/cucumber_expression_generator_test.js
123 silly gunzTarPerm extractEntry test/cucumber_expression_regexp_test.js
124 silly gunzTarPerm extractEntry test/cucumber_expression_test.js
125 silly gunzTarPerm extractEntry test/custom_parameter_type_test.js
126 silly gunzTarPerm extractEntry test/expression_examples_test.js
127 silly gunzTarPerm extractEntry test/regular_expression_test.js
128 silly gunzTarPerm extractEntry test/mocha.opts
129 silly gentlyRm /usr/local/lib/node_modules/.staging/cucumber-expressions-343a18f0/node_modules is being purged
130 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/.staging/cucumber-expressions-343a18f0/node_modules
131 silly doParallel preinstall 1
132 silly preinstall cucumber-expressions@3.0.0 /usr/local/lib/node_modules/.staging/cucumber-expressions-343a18f0
133 info lifecycle cucumber-expressions@3.0.0~preinstall: cucumber-expressions@3.0.0
134 silly lifecycle cucumber-expressions@3.0.0~preinstall: no script for preinstall, continuing
135 silly doReverseSerial remove 0
136 silly doSerial move 0
137 silly doSerial finalize 1
138 silly finalize /usr/local/lib/node_modules/cucumber-expressions
139 silly doSerial build 1
140 silly build cucumber-expressions@3.0.0
141 info linkStuff cucumber-expressions@3.0.0
142 silly linkStuff cucumber-expressions@3.0.0 has /usr/local/lib/node_modules as its parent node_modules
143 silly linkStuff cucumber-expressions@3.0.0 is part of a global install
144 silly linkStuff cucumber-expressions@3.0.0 is installed into a global node_modules
145 silly linkStuff cucumber-expressions@3.0.0 is installed into the top-level global node_modules
146 verbose linkBins cucumber-expressions@3.0.0
147 verbose linkMans cucumber-expressions@3.0.0
148 silly doSerial global-link 0
149 silly doParallel update-linked 0
150 silly doSerial install 1
151 silly install cucumber-expressions@3.0.0 /usr/local/lib/node_modules/.staging/cucumber-expressions-343a18f0
152 info lifecycle cucumber-expressions@3.0.0~install: cucumber-expressions@3.0.0
153 silly lifecycle cucumber-expressions@3.0.0~install: no script for install, continuing
154 silly doSerial postinstall 1
155 silly postinstall cucumber-expressions@3.0.0 /usr/local/lib/node_modules/.staging/cucumber-expressions-343a18f0
156 info lifecycle cucumber-expressions@3.0.0~postinstall: cucumber-expressions@3.0.0
157 verbose lifecycle cucumber-expressions@3.0.0~postinstall: unsafe-perm in lifecycle false
158 verbose lifecycle cucumber-expressions@3.0.0~postinstall: PATH: /usr/share/npm/bin/node-gyp-bin:/usr/local/lib/node_modules/cucumber-expressions/node_modules/.bin:/usr/local/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
159 verbose lifecycle cucumber-expressions@3.0.0~postinstall: CWD: /usr/local/lib/node_modules/cucumber-expressions
160 silly lifecycle cucumber-expressions@3.0.0~postinstall: Args: [ '-c', 'node scripts/postinstall.js' ]
161 info lifecycle cucumber-expressions@3.0.0~postinstall: Failed to exec postinstall script
162 verbose unlock done using /home/chrx/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
163 silly rollbackFailedOptional Starting
164 silly rollbackFailedOptional Finishing
165 silly runTopLevelLifecycles Starting
166 silly runTopLevelLifecycles Finishing
167 silly install printInstalled
168 verbose stack Error: cucumber-expressions@3.0.0 postinstall: `node scripts/postinstall.js`
168 verbose stack spawn ENOENT
168 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
168 verbose stack     at emitTwo (events.js:87:13)
168 verbose stack     at ChildProcess.emit (events.js:172:7)
168 verbose stack     at maybeClose (internal/child_process.js:821:16)
168 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
169 verbose pkgid cucumber-expressions@3.0.0
170 verbose cwd /home/chrx/scm/oss/protractor-cucumber
171 error Linux 4.9.4-galliumos-braswell
172 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "cucumber-expressions"
173 error node v4.2.6
174 error npm  v3.5.2
175 error file sh
176 error code ELIFECYCLE
177 error errno ENOENT
178 error syscall spawn
179 error cucumber-expressions@3.0.0 postinstall: `node scripts/postinstall.js`
179 error spawn ENOENT
180 error Failed at the cucumber-expressions@3.0.0 postinstall script 'node scripts/postinstall.js'.
180 error Make sure you have the latest version of node.js and npm installed.
180 error If you do, this is most likely a problem with the cucumber-expressions package,
180 error not with npm itself.
180 error Tell the author that this fails on your system:
180 error     node scripts/postinstall.js
180 error You can get information on how to open an issue for this project with:
180 error     npm bugs cucumber-expressions
180 error Or if that isn't available, you can get their info via:
180 error     npm owner ls cucumber-expressions
180 error There is likely additional logging output above.
181 verbose exit [ 1, true ]

**Comment by aslakhellesoy** [comment]
Hey @paul-hammant 

I see you're on Node 4.2.6. Any chance you could try with Node 5, 6 or 7? We *could* add support for older Node versions, but it's not very high priority.

**Comment by aslakhellesoy** [comment]
I tried to reproduce this, but wasn't able to:

```
nvm install 4.2.6
npm install --global npm@3.5.2
npm install cucumber
```

I got no errors. Can you provide details about how to reproduce?

**Comment by paul-hammant** [comment]
It's a lowly 2GB chromebook I keep at work - will report back next week, dude

**Comment by aslakhellesoy** [comment]
Hey @paul-hammant any update here?

**Comment by paul-hammant** [comment]
I think you hit it right - Node versions. I'm struggling to get the wee GalliumOS machine to obey me versus deps to install. Just close this, dude.
