### ISSUE TITLE
question: quoted-string param types?

### ISSUE THREAD

**Issue by tony-kerz** [cucumber/cucumber-expressions-javascript#3]
hi, i just came across cuke-expressions as a more readable alternative to regular-expressions.
i like the idea because in most cases it seems like regular expressions were over-powered for what is required, and they end up taking more brain cycles to parse visually.

i often use single and double quotes around string parameters as a visual indicator that they are parameters to a step:

example:
```
Given the following file is created at path '/tmp/udx/test.dat' with contents:
```
then step definition would look like:
```
Given(/^the following file is created at path '([^']+)' with contents:$/, (pathString, contentsString) => {...}
```
i am having trouble finding it now, but i swear i saw an example that used a type like `doubleQuotedString`, something like:
```
Given('the following file is created at path {doubleQuotedString} with contents:', (pathString, contentsString) => 
```
is that actually built in, or was that in an example of a custom type?
for my purposes, i was kind of looking for a couple of helper types like `doubleQuotedString` and `singleQuotedString`...

**Comment by aslakhellesoy** [comment]
Great minds think alike! I've added an issue for that over at the monorepo: cucumber/cucumber#218
